### ISSUE TITLE
Upgrading from Xdebug 2 to 3

### ISSUE THREAD

**Issue by AndriyKarpov** [lemberg/draft-environment#231]
Hi.
It would be nice to update Xdebug configurations to match with the 3rd version. If I not mistaken they should look like this:

**Old**
```
xdebug:
    xdebug.remote_enable: 'On'
    xdebug.remote_connect_back: 'On'
    xdebug.remote_log: /var/log/draft/php_xdebug_remote.log
```

**New**
```
xdebug:
    xdebug.mode: debug
    xdebug.discover_client_host: true
    xdebug.log: /var/log/draft/php_xdebug.log
```
